### ISSUE TITLE
Switch to electron again

### ISSUE THREAD

**Issue by cleverer** [scout-ch/midata-cypress#4]
When https://github.com/cypress-io/cypress/issues/5139 is resolved, we can switch back to using electron in the `cypress` service

**Comment by simfeld** [comment]
Did you experience any issues as described in the linked cypress issue in our case? As far as I can see, our GitHub Actions runs use headless Electron and seem to be working fine at the moment.

**Comment by cleverer** [comment]
Ah yes, i was referring to the docker-compose file for local developement. I think the latest update even broke chrome due to memory issues.

**Comment by cleverer** [comment]
This will be adressed in #17
